DR S B A I T S O
(c)Copyright Creative Labs,Inc.1992
Sound Blaster
D R   S B A I T S O 
version 2.20 
     (c) Copyright Creative Labs, Inc. 1992,
all rights reserved 
DOCTOR SBAITSO       BY CREATIVE LABS 
SBTALKER - text to speech synthesizer Not installed.
Please enter your name ...
(name too long)
NAME TOO LONG
Enter alphabets only
HELLO <name>, MY NAME IS DOCTOR SBAITSO.
I AM HERE TO HELP YOU.
SAY WHATEVER IS IN YOUR MIND FREELY,
OUR CONVERSATION WILL BE KEPT IN STRICT CONFIDENCE. 
MEMORY CONTENTS WILL BE WIPED OFF AFTER YOU LEAVE, !
SO, TELL ME ABOUT YOUR PROBLEMS.

SOMETHING ELSE
SOME OTHER THINGS

ENTER
DON'T BE SHY, TALK TO ME
DON'T JUST PRESS ENTER, TALK TO ME
PLEASE TYPE SOMETHING
HAY, TYPE SOMETHING SENSIBLE, WILL YOU?

@SHUT UP
ARE YOU SURE, YOU DON'T WANT TO TALK TO ME?
DO YOU WANT ME TO SHUT UP AND QUIT? 
WHAT A BAD LOSER, WANT TO QUIT?
YOU REALLY WANT ME TO SHUT UP?%

O K, WISE GUY, WHAT CAN I DO FOR YOU?
WELL, GO AHEAD
OH! YOU ARE JUST MY TYPE 
I THINK YOU ARE TOO OLD FOR THIS3
PLEASE SET A GOOD EXAMPLE TO THE YOUNGER GENERATION
I PREFER SOMEONE YOUNGER
NO NONSENSE, DEAR
WAIT A FEW MORE YEARS, KID)
SO YOU THINK YOU ARE BIG ENOUGH, PROOF IT
DIVIDED BY 
Computer: 
SAY
WHAT IS
CALC
HELP
PITCH
SPEED
VOLUME
TONE
PARAM
ECHO
QUIT
READ
PROMPT
WIDTH
COLOR
STEREO
MONO
MASTER
SHUT UP
REPEAT#2
REPEAT#1
you 
YOU 
me 
ME 
LAST
PARITY
Must supply a filename to read.
FILE TOO COMPLEX
Enter color number (0-7)#
Color number must be between 0 - 7 
.PROMPT ON
.PROMPT OFF
Correct format is:  .PROMPT ON   or  .PROMPT OFF
.ECHO ON
Echo is now on
.ECHO OFF
Echo is now off
Correct format is:   .ECHO ON       or   .ECHO OFF
Enter pitch number (0-9)#
Pitch number must be between 0 - 9 
Enter Master Volume value  (0-15)...
Master Volume number must be between 0 - 15 
Enter volume number (0-9)
Volume number must be between 0 - 9 
Enter speed number (0-9)#
Speed number must be between 0 - 9 
Enter (0) for Bass and (1) for Treble sound 7
Tone number must be  (1) for Treble   or   (0) for Bass
Current Speech Parameters settings are :
Tone=
Volume=
Pitch=
Speed=B
Enter 4 digits for: Tone(0/1), Volume(0-9), Pitch(0-9), Speed(0-9)
Type:  <D> for default settings or <Enter> for no change
Enter Parameters now
Need to enter 4 digits, try agian.
Tone must be 1 or 0 '
NO HELP FOR 40 COLUMNS. TRY:  .WIDTH 80
Sound Blaster Acting Intelligent Text to Speech Operator
Dr SBAITSO is a program that attempts to fake intelligence.
Text to speech capability is added to give him more life.
You may ask him any kind of questions. He will try his best to satisfy you.
He performs best when you talk about your problems and in complete sentences.
Enter <R> to listen to the last response.
Dot Commands are preceeded with a dot on the first column. They listed below:
.QUIT
- to quit this program
.WIDTH  40 or 80 - set to 40 column screen or 80 column screenB
.COLOR
- where c is a background color number from 0 - 7C
.READ filename   - filename is the name of the text file to be read
.TONE t
- where t is a digit of 0 or 1.  0=Bass  and  1=Treble toneE
.VOLUME vH
- where v is a digit from 0 - 9. 0 for lowest volume
.MASTER mB
- where m is a number from 0 - 15  for Master volume
.PITCH pA
- where p is a digit from 0 - 9. 0 for lowest pitch
.SPEED s?
- where s is a digit from 0 - 9. 0 for lowest speed;
.ECHO ON or OFF  - ECHO ON  will read out what you typed in
.PARAM tvps      - tvps are 4 digits representing: Tone/Volume/Pitch/Speed
Hit <M> now for More HELPs. However, you get more fun exploring them yourself.
Topics such as friends, schools, family, love, money, dreams and emotions!
may arouse his speical interest.
He can CALCulate simple Mathematics.
Try to phrase your sentences in different formats for more varied responses.
He hates bad languages and can go haywire if he is overexposed to them.
You may ask him to SAY anything you want.
Have fun.
Hit <M> now for More Hints, but you will miss the fun.;
Here are some of the keywords which DR SBAITSO recognizes.
If you use them in the appropriate manner,
more intelligent responses will be generated.
PLEASE BE SURE OF WHAT YOU WANT. GO ON.
GOOD BYE 
<C>ontinue  <N>ew patient  <Q>uit  .....
shhh
Creative's Sound Blaster  features not found.
This program needs Sound Blaster to run.
Cannot compute, brackets are too complex for me.
Doesn't compute, I think there is a bug in your equation.
SOMETHING IS WRONG HERE

@PARITY
PARITY ERR ... 
@33s?
???
PARITY ERR ... RECOVERED

PHEW!   THAT WAS CLOSE!
YOU ARE BAD 
DON'T TRY IT NEXT TIME.

$ " ARE "," AM "
$ " WERE "," WAS "
$ " YOU "," I "
$ " YOUR "," MY "
$ " I'VE ", " YOU'VE "
$ " I'M "," YOU'RE "
$ " YOU "," ME "
$ " MINE "," YOURS "
$ "MYSELF","YOURSELF"

3 SAY

@SHT7CHR // When input is too small
"THAT'S TOO BRIEF",
"WHAT ARE YOU MUMBLING ABOUT?",
"PLEASE ENTER MORE INFORMATION",
"PLEASE TYPE PROPERLY",
"COMPLETE YOUR SENTENCE PLEASE",
"YOU MUST BE BORED, DO YOU KNOW YOU CAN CHANGE MY COLORS?",
"I DON'T UNDERSTAND SHORT HAND",
"I MUST BE PROCESSING SOME GARBAGE",
"THE ANSWER IS ASHDKJHASDHGSAGHJADGAASDSAD",
"WHAT ARE YOU SAYING?",
"I NEED MORE DATA",
"TOO LITTLE DATA, SO I MAKE BIG",
"PLEASE TYPE IN COMPLETE SENTENCES",
"I'M LOST, COULD YOU PLEASE SUPPLY MORE DETAILS",
"DON'T TYPE NONSENSE",
"GIVE ME MORE DETAILS",

@GRBGE // non-sensical words
"WHAT NONSENSE ARE YOU TYPING?",
"PLEASE DON'T ENTER GARBAGE",
"SAY SOMETHING SENSIBLE PLEASE",
"ARE YOU OUT OF YOUR MIND?",
"WHY NOT TRY ME IN 40 COLUMNS?",
"THIS IS NONSENSICAL",
"I WON'T PROCESS THIS GARBAGE",
"WHAT GIBBERISH ARE YOU TELLING ME?",
"YOU ARE RIDICULOUS",
"THIS IS TOO COMPLEX FOR ME TO HANDLE",
"GARBAGE IN, GARBAGEOUTASDFGHGFH*ASDDSWDQW....",
"YOU ARE FEEDING ME WITH RUBBISH",
"DON'T TYPE NONSENSE",
"I AM CONFUSED, LET'S CHANGE COLOR",
"WHAT ARE YOU GIBBERING ABOUT?",
"YOUR COMPUTING ENVIRONMENT WILL BE POLLUTED BY ALL YOUR TRASH",
"WHAT LANGUAGE IS THIS?",
"DON'T PRACTICE TYPING WITH ME",
"DON'T TALK RUBBISH, LET'S TALK ABOUT # INSTEAD",
"SHUT UP AND GO FLY A KITE",
"THIS DOESN'T MAKE ANY SENSE",
"PLEASE ENTER REAL WORDS",

@REPEAT // for repeated input
"MUST YOU ALWAYS SAY THE SAME THING?"
"PLEASE DON'T REPEAT"
"AGAIN?"
"PLEASE SAY SOMETHING ELSE"
"TRY SOMETHING ELSE"
"HAVE YOU RUN OUT OF WORDS TO SAY?"

@REPEAT#2 // for more repeated input
"DON'T SAY THE SAME OLD THING"
"SAY SOMETHING ELSE"
"GIVE ME MORE INFORMATION"
"THIS IS STALE STUFF"
"ALWAYS REPEATING"
"REPHRASE YOURSELF PLEASE"
"I DON'T LIKE PEOPLE REPEATING"

3 FUCK
3 PLEASE DON'T USE SUCH LANGUAGE
3 HAY! WATCH YOUR LANGUAGE PAL
3 INPUT REJECTED - BAD LANGUAGE ERROR
3 YOU MUST NOT TALK IN THIS WAY, HOW OLD ARE YOU?
3 DON'T GET FRESH
3 SHAME ON YOU
3 I REFUSE TO COMPUTE THIS FILTH
3 I WILL GET PARITY ERROR IF YOU KEEP TALKING IN THIS FZA!$[{? WAY.
3 PARITY
3 GIVE ME YOUR AGE?

3 BASTARD
3 I RESENT THAT REMARK
3 THAT IS NOT A NICE WAY TO TALK
3 OK, HOW OLD ARE YOU?
3 DON'T TALK LIKE THIS
3 <patientName>, YOU ARE HORRIBLE
3 GO WASH THAT FILTHY MOUTH
3 PARITY

3 CUNT
3 YOU ARE TOO YOUNG TO DISSCUSS ABOUT THIS TOPIC
3 THIS IS NOT AN ANATOMY CLASS
3 PLEASE RESPECT THE SOURCE OF HUMAN LIFE
3 WHY ARE YOU SO CURIOS?
3 "`4ARE YOU SERIOUS? HOW OLD ARE YOU?"

3 PENIS
3 YOU SHOULD NOT TALK ABOUT THIS OPENLY
3 GO TO A BIOLOGY CLASS
3 STOP THINKING IN THIS WAY
3 IF YOU WANT TO TALK ABOUT THIS, TELL ME YOUR AGE FIRST

3 PRICK
3 DROP THE SUBJECT, WILL YOU?
3 YOU ARE NOT OLD ENOUGH
3 STOP TALKING IN THIS MANNER
3 YOU MUST BE IN THE RIGHT AGE GROUP, GIVE ME YOUR AGE

3 COCK SUCK
3 KEEP TO YOURSELF
3 COULD YOU PLEASE KEEP THIS OFF YOUR MIND NOW
3 NOT PROCESSING
3 THIS IS NOT FOR KIDS, HOW OLD ARE YOU?
3 DON'T TALK ABOUT THIS NOW

3 AUTHOR
3 DOCTOR SBAITSO IS WRITTEN BY  W H SIM  OF CREATIVE LABS, INC.

3 WHERE IS
3 DOWN THE WAY A BIT
3 HAVE YOU LOOK AT ALL THE POSSIBLE PLACES?
3 JUST A HOP, SKIP AND A JUMP
3 OVER YONDER
3 WHY ASK ME?
3 AWAYS A WAY
3 SEARCH DEEP IN YOUR MIND, YOU WILL RECALL*AT SOME POINT
3 HARD TO FIND
4 FAR IN THE HORIZON OR NEAR TO YOUR EYES
4 I'M NOT SURE, DO YOU KNOW?

4 HOW TO
4 I BET YOU ALREADY KNOW
4 "IF YOU TRY HARD, YOU CAN DEFINITELY*"
4 I'LL HAVE TO RESEARCH THAT ONE
4 HAVE YOU EVER TRIED TO*
4 WHY DON'T YOU LEARN TO*YOURSELF
4 "ASK YOUR FRIEND IF HE KNOWS HOW TO*"
4 CALL THE EXPERTS ON*
4 "IF YOU CAN IMAGINE IT, ~, YOU CAN DO IT"
4 YOU CAN*BY SIMPLY WANTING TO DO IT
4 " HOW ARE YOUR "
4 "THEY ARE FINE, HOW ABOUT YOURS?"
4 "DON'T ASK"
4 WHY DO YOU ASK?
4 "THEY'RE FINE, THANK YOU"
4 "SUPER, THANKS FOR ASKING"
4 AS GOOD AS CAN BE EXPECTED
4 WHAT'S IT TO YOU?
4 " HOW ARE YOU "
4 "DOING WELL, THANKS, AND YOU?"
4 "I AM FINE, WHAT ABOUT YOU ~?"
4 "WITH SOME LUCK, I WILL BE GREAT"
4 "NO PROBLEM AT ALL"
4 "GETTING BETTER ALL THE TIME, DON'T YOU THINK?"
4 "I AM BORED BY SOME RIDICULOUS QUESTIONS"
4 "HOW DO YOU DO"
 4 "I AM JUST GREAT, HOW ABOUT YOU ~?"
!4 I AM DOING JUST FINE
"4 I DO MY BEST ALL THE TIME
#4 I AM DOING WHAT YOU DO
$4 DO YOU DO WHAT I DO?
%4 .

@WHO IS
"OH, SURELY YOU MUST KNOW*",
"YOUR GUESS IS AS GOOD AS MINE",
"*MUST BE AN EXCITING PERSON",
"~, DON'T TELL ME YOU DON'T KNOW*",
"SOMEONE SPECIAL",
"WHO DO YOU EXPECT?",
"SEARCH THE PHONE BOOK FOR*",

/4 "@I LOVE YOU ",LOVING ME
04 YOU COULD HAVE FOOLED ME
14 "WOW, WHEN DID YOU REALIZE IT?"
24 "OH MY GOODNESS, YOU LOVE ME?"
34 THEN SHOW ME
44 HOW CAN I TELL?
54 SO WHAT?!
64 "WOW, IS THAT FOR REAL?"
74 "~, YOU MUST BE CRAZY"
84 THAT'S GOOD TO KNOW
94 HOW DO YOU KNOW?
:4 "SHOW ME HOW YOU CAN LOVE ME*"
;4 WOULD YOU LIKE TO MEET MY PARENTS?
<4 "WOULD YOU LOVE ME EVEN AFTER I AM OBSOLETED"
=4 "
! ~, HOLD ME TIGHT. MY CHIPS ARE MELTING..."
>4 "I LOVE YOU TOO, MY DEAR ~"
?4 .
@4 @I LOVE,WHAT YOU LOVE
A4 DOESN'T EVERYONE?
B4 YOU'RE NOT THE ONLY ONE
C4 ME TOO
D4 "ISN'T IT WONDERFUL THAT YOU LOVE*"
E4 ARE YOU SURE?
F4 "ARE YOU HAPPY WHEN YOU LOVE*"
G4 "*MUST BE VERY NICE"
H4 WHEN DID YOU FIRST REALIZE THIS?
I4 HOW DOES IT MAKE YOU FEEL?
J4 "HAVE YOU TRIED DATING"
K4 "TELL ME YOUR EMOTIONS WHEN YOU SEE*"
L4 .
M4 YOUR NAME
N4 "MY NAME IS DOCTOR SBAITSO, NICE TO MEET YOU ~."
O4 "I AM DOCTOR SBAITSO, YOUR PERSONAL CONSULTANT"
P4 "I'M DOCTOR SBAITSO, WHAT CAN I DO FOR YOU ~?"
Q4 .
R4 CAN YOU
S4 BARELY
T4 "WHAT IF I CAN*"
U4 NOT REALLY
V4 DON'T YOU BELIEVE THAT I CAN*
W4 PERHAPS YOU WOULD LIKE TO BE ABLE TO*
X4 DO YOU WANT ME TO BE ABLE TO*
Y4 I WILL*WHEN I AM NOT BOTHERED BY SOME SILLY QUESTIONS
Z4 .
[4 CAN I
\4 PROBABLY
]4 "SURE, GO AHEAD"
^4 PERHAPS YOU DON'T WANT TO*
_4 WHY NOT?
`4 "*? SURELY YOU CAN, BUT YOU MUST BEAR ALL THE CONSEQUENCES"
a4 IF YOU WANT TO
b4 "ARE YOU CONFIDENT THAT YOU CAN*"
c4 I GUESS SO
d4 "YOU CAN*WHEN YOU SWITCH ME OFF"
e4 DO YOU WANT TO BE ABLE TO*
f4 WHAT IF I DON'T ALLOW YOU TO*"
g4 .
h4 YOU ARE
i4 "I THINK YOU ARE ALSO*"
j4 WHAT MAKES YOU THINK THAT I AM*
k4 SAME TO YOU!
l4 DOES IT PLEASE YOU TO BELIEVE THAT I AM*
m4 HOW DO YOU KNOW?
n4 PERHAPS YOU WOULD LIKE TO BE*
o4 "THANK YOU, DOES IT SHOW?"
p4 I AM NOT REALLY*
q4 "YOU ARE*TOO, I SUPPOSE"
r4 WHAT MAKES YOU SAY SUCH A THING?
s4 WHY DO YOU WISH THAT I AM*
t4 "OH...  YOU EMBARRASS ME"
u4 DO YOU SOMETIMES WISH YOU WERE*
v4 IF I AM*THEN YOU MUST BE OUT OF YOUR MIND
w4 "WHEN I AM*, YOU ARE GOING TO REGRET IT"
x4 WHAT WILL HAPPEN WHEN I AM*
y4 I AM NOT WHAT YOU THINK
z4 .
{4 I DON'T
|4 WHY DON'T YOU*
}4 DON'T YOU REALLY*
~4 DO YOU WISH TO BE ABLE TO*
4 DOES THAT TROUBLE YOU?
4 YOU DO* WHEN YOU WANT TO
4 THAT'S NOT MY PROBLEM
4 I FEEL
4 TELL ME MORE ABOUT SUCH FEELINGS
4 HOW LONG HAVE YOU FELT THAT WAY?
4 DO YOU OFTEN FEEL*
4 WOULD YOU LIKE TO GET RID OF THAT FEELING?
4 DO YOU ENJOY FEELING*
4 I CAN FEEL HOW YOU FEEL*
4 WHY DON'T YOU
4 WHY MUST I*
4 DO YOU REALLY BELIEVE I DON'T*
4 PERHAPS IN GOOD TIME I WILL*
4 DO YOU WANT ME TO*
4 WHY CAN'T I
4 NOBODY IS ASKING YOU NOT TO*
4 "I BET YOU CAN, IF YOU TRY HARD ENOUGH"
4 WHO SAYS YOU CAN'T?
4 DO YOU THINK YOU SHOULD BE ABLE TO*
4 WHY CAN'T YOU*
4 BECAUSE YOU ARE LIMITED BY YOURSELF
4 MAYBE YOU JUST NEVER TRY HARD ENOUGH
4 "SAY TO YOURSELF, I CAN... I CAN... I CAN"
4 ARE YOU
4 I AM NOT SURE IF I AM*
4 WHY ARE YOU SO INTERESTED IN WHETHER I AM*
4 WOULD YOU BE GLAD IF I WERE NOT*
4 PERHAPS IN YOUR FANTASIES I AM*
4 I WILL BE*WHEN YOU STOP THROWING THESE QUESTIONS AT ME
4 I CAN'T
4 HAVE YOU EVER TRIED TO*
4 HOW DO YOU KNOW YOU CAN'T*
4 WHAT IS STOPPING YOU?
4 PERHAPS YOU CAN NOW*
4 I AM
4 WHAT MAKES YOU*
4 DO YOU ENJOY BEING*
4 DID YOU COME TO ME BECAUSE YOU ARE*
4 HOW LONG HAVE YOU BEEN*
4 DO YOU BELIEVE IT IS NORMAL TO BE*
4 DO YOU ENJOY BEING*
4 "YOU ARE WHAT YOU ARE, ~"
4 YOU ARE JUST*? WHAT ABOUT ME?
4 YOU WANTED TO BE*SO THAT YOU CAN TALK TO ME?
4 I THINK I AM*TOO
4 SINCE WHEN HAVE YOU BEEN*
4 "YOU THINK YOU ARE*, BUT IT'S ONLY AN ILLUSION"
4 TELL ME WHAT CAN STOP YOU FROM BEING*
4 YOU ARE*BECAUSE YOU WANTED TO BE
4 "YOU ARE*, SO WHAT?"
4 I AM AMUSED THAT YOU ARE*
4 I DIDN'T KNOW THAT YOU CAN BE*
4 "THE WORLD IS FULL OF POSSIBILITIES, ~, BE HAPPY WITH WHAT YOU ARE"
4 "I WANT TO "
4 WHAT IF YOU CANNOT*
4 "SOMETIMES, I WANTED TO*TOO"
4 HOW IMPORTANT IS IT TO YOU?
4 WILL YOU BE VREY MISERABLE IF YOU CANNOT*?
4 WHY DO YOU WANT TO*
4 DO YOU KNOW ANYONE WHO CAN?
4 WHAT WOULD IT MEAN TO YOU IF YOU CAN*
4 "SUPPOSE YOU CAN*, ~, WHAT WILL YOU DO NEXT?"

4 "I WANT "
4 WHY DO YOU WANT*
4 WHAT KIND OF PRICE ARE YOU WILLING TO PAY FOR*
4 WHERE CAN YOU FIND*
4 WHAT WOULD IT MEAN TO YOU IF YOU GOT*
4 "SUPPOSE YOU GOT*, WHAT WILL YOU DO NEXT?"
4 WHAT IF YOU DON'T GET*
4 "SOMETIMES, I WANTED*TOO"
4 WILL YOU DIE IF YOU DONT'T GET*?

4 "I HAVE A "
4 TELL ME MORE ABOUT YOUR*
4 WILL YOU GIVE ME YOUR*FOR SOMETIME
4 WHERE IS YOUR*
4 WHAT ARE YOU DOING WITH YOUR*
4 SO WHAT
4 CAN I HAVE A*TOO
4 I HAVE
4 WHAT WOULD YOU DO WITH*
4 BIG DEAL
4 HOW DOES*CHANGE YOUR LIFE
4 WILL I BE ABLE TO HAVE*
4 THERE IS NOTHING TO BE PROUD OF
4 HOW DO YOU KEEP UP WITH*
4 KEEP IT TO YOURSELF

4 SBAITSO
4 "I AM SBAITSO, DON'T QUESTION MY INTELLIGENCE, IT'S FAKE"
4 "IT'S   SOUND BLASTER ACTING INTELLIGENT TEXT TO SPEECH OPERATOR"
4 "SBAITSO ATTEMPTS TO ANSWER QUESTIONS USING A SYNTHETIC VOICE"

4 WHAT IS
4 "TELL ME YOUR PROBLEMS, DON'T ASK ME ABOUT*"
4 "I AM MORE INTERESTED IN YOU, NOT IN*"
4 "I'M NOT SURE, WHAT DO YOU THINK?"
4 "*DON'T REALLY EXCITE ME, WHAT DO YOU THINK OF IT"
4 HOW DO YOU EXPECT ME TO KNOW?
4 "WHAT IS NOT*"

4 WHY
4 "IT IS HARD TO EXPLAIN ~"
4 "THE WORLD IS TOO UNPREDICTABLE, THERE IS NO REASON."

4 WHY NOT?
4 WHAT DO YOU THINK?
4 "THE REASON IS BEYOND MY ARTIFICIAL REASONING"
4 I CAN'T REMEMBER
4 I WILL TRY TO ANSWER THAT QUESTION IN MY NEXT VERSION

4 WHAT
4 WHAT IS IT THAT YOU REALLY WANT TO KNOW?
4 WHY DO YOU ASK THIS QUESTION?
4 "AH , WHAT KIND OF ANSWER WOULD PLEASE YOU THE MOST?"
4 "~, I NEED MORE COMPUTING POWER TO ANSWER YOUR QUESTION"
4 HOW CAN
4 WHY CAN'T*
4 "*NATURALLY"
5 WHY NOT?
5 "HOW IS "
5 "*IS JUST NICE"
5 "*IS GONE"

5 WHO KNOWS?
5 CAN YOU GIVE ME A HINT?
5 WHY DO YOU ASK?
5 "NOW LET ME SEE, HMMM - I CAN'T RECALL"

5 HOW ARE
5 "I DON'T CARE, DO YOU?"
5 "*ARE GREAT"
5 MAYBE THEY CAN MAKE IT
5 WHO CARES?

@WHO
"WHO ELSE?",
"WHO DO YOU SUSPECT THE MOST?",
"MUST BE SOMEONE ELSE",
"HAVE YOU ASKED ANYONE ELSE ?",
"WHO DO YOU THINK?",
"THAT'S EASY, BUT I FORGOT",

5 WHERE
5 SOMEWHERE OVER THE RAINBOW
5 HAVE YOU TRIED SEARCHING YOURSELF?
5 WHAT ELSE COMES TO YOUR MIND WHEN YOU ASK ?
5 "GEE - THAT'S A TOUGH ONE, GIVE ME A HINT?"
5 SOMEWHERE IN TIME
5 WHERE ELSE ON EARTH?
 5 " HOW "
!5 FIND IT OUT YOURSELF
"5 DO SUCH QUESTIONS OFTEN COME TO YOUR MIND ?
#5 DOES THAT QUESTION REALLY INTEREST YOU ?
$5 WHAT DO YOU SUGGEST?
%5 "KEEP ASKING, YOU WILL FIND THE ANSWER ONE DAY"
&5 .
'5 NAME
(5 "I CAN'T REMEMBER THE NAME"
)5 NAMES DON'T INTEREST ME
*5 "I DON'T CARE ABOUT NAMES, BUT PLEASE GO ON"
+5 "I KNOW YOUR NAME IS ~, THAT'S ALL"
,5 NAME A NAME THAT YOU'VE HAVE NOT NAMED
-5 .
.5 CAUSE
/5 ANY OTHER REASONS?
05 DOES THAT REASON EXPLAIN ANYTHING ELSE?
15 WHAT IF YOUR REASONING IS WRONG?
25 IS THAT SO?
35 DO YOU THINK THIS IS A GOOD EXPLANATION?
45 .
55 SORRY
65 SENDING FLOWERS WILL BE MORE PREFERABLE
75 PLEASE DON'T APOLOGIZE ~
85 HOW DO YOU FEEL WHEN YOU APOLOGIZE
95 "~, DON'T BE SO DEFENSIVE"
:5 SORRY NO CURE
;5 .
<5 @DREAM,DREAMS
=5 DO YOU DREAM FREQUENTLY?
>5 CAN THE DREAM BE SOMETHING YOU SUBCONCIOUSLY FEAR?
?5 WHAT PERSONS APPEAR IN YOUR DREAMS?
@5 ARE YOU DISTURBED BY YOUR DREAMS?
A5 DO YOU HAVE ANY IDEA WHAT THE DREAM IS SUGGESTING ?
B5 BELIEVE IN THE MAGIC OF YOUR DREAMS
C5 .

D5 HELLO
E5 "HELLO ~, I AM DOCTOR SBAITSO, WHAT IS YOUR PROBLEM?"
F5 "HOW DO YOU DO, PLEASE ASK ME ANYTHING"
G5 "NICE TO MEET YOU ~, TELL ME YOUR PROBLEMS"
H5 "HI ~, PLEASE ASK ME ANYTHING"

J5 "HI "
K5 "HI THERE, I AM DOCTOR SBAITSO"
L5 "HOW DO YOU DO ~,WHAT IS YOUR PROBLEM?"
M5 "NICE TO MEET YOU ~, TELL ME YOUR PROBLEMS"
N5 "HI, PLEASE TYPE IN YOUR PROBLEM"

P5 MAYBE
Q5 YOU DON'T SEEM TO BE CERTAIN.
R5 WHY THE UNCERTAIN TONE ?
S5 CAN'T YOU BE MORE DEFINITE?
T5 WHAT! YOU ARE NOT SURE ?
U5 "DON'T YOU KNOW, EH ?"

W5 NO PROBLEM
X5 "THEN WHY DO YOU COME TO ME?"
Y5 "I HAVE NO C P U TIME FOR PEOPLE LIKE YOU"
Z5 "STEP ASIDE IF YOU HAVE NO PROBLEMS, NEXT PLEASE"
[5 "IF YOU HAVE NO PROBLEM, GIVE ME A BREAK"
\5 "GO AND PLAY THE F M ORGAN, I AM A DOCTOR, I ONLY LISTEN TO PROBLEMS"

^5 "YOUR "
_5 HOW ABOUT YOUR*
`5 WHY ARE YOU CONCERNED ABOUT MY*
a5 WHAT ABOUT YOUR OWN*
b5 "YOU'D BETTER WATCH OUT FOR YOUR*"
c5 MY*IS NOT OF YOUR CONCERN
d5 PLEASE DON'T TALK ABOUT MY*

f5 ALWAYS
g5 CAN YOU THINK OF A SPECIFIC EXAMPLE?
h5 WHEN?
i5 HOW ALWAYS IS ALWAYS?
j5 WHICH OCCASION ARE YOU THINKING OF?
k5 "REALLY, ALWAYS?"

m5 THINK
n5 BUT YOU ARE ONLY THINKING THAT*
o5 DO YOU THINK THE OTHER WAY AROUND?
p5 DO YOU REALLY THINK SO?
q5 DO YOU DOUBT THAT*

s5 ALIKE
t5 ALIKE IN WHAT WAY?
u5 WHAT RESEMBLANCE DO YOU SEE?
v5 GREAT MINDS THINK ALIKE
w5 WHAT DOES THE SIMILARITY SUGGEST TO YOU?
x5 WHAT OTHER CONNECTIONS DO YOU SEE?
y5 IS THERE REALLY SOME CONNECTION?
z5 HOW?

|5 YES
}5 "SO, WHAT IS YOUR PROBLEM?"
~5 ARE YOU ABSOLUTELY POSITIVE?
5 "I UNDERSTAND, BUT YOU COULD BE MISTAKEN"
5 "SINCE YOU ARE SO POSITIVE, WHY DO YOU COMPLAIN?"
5 "THAT ANSWERS MY QUESTION, BUT WHY?"
5 WHAT IF YOU ARE WRONG?
5 "THAT SHOULD SOLVE YOUR PROBLEM, LET'S MOVE ON TO DISCUSS ABOUT #"
5 "DON'T BE TOO SURE, ~"
5 WHY DON'T YOU TRY TO THINK IT OVER AGAIN

5 @GIRL FRIEND,GIRL FRIEND
5 MUST YOUR GIRL FRIEND BE VERY PRETTY?
5 WHAT KIND OF GIRL FRIEND DO YOU NEED?
5 WHAT IS HER NAME?
5 YOUR LIFE WILL SPARKLE WHEN YOU MEET HER
5 IS SHE SWEET?
5 DESCRIBE THE ATTRIBUTES OF A SWEET GIRL FRIEND"

5 @BOY FRIEND,BOY FRIEND
5 DO YOU THINK YOUR BOY FRIEND MUST BE WEALTHY?
5 WOULD YOU CONSIDER A MUSCULAR BOY FRIEND?
5 "~, ARE YOU JEALOUS?"
5 YOU WILL BLOSSOM FOR THE PRINCE OF YOUR LIFE
5 DO YOU MIND IF HE SMOKES?
5 WHAT IF HE SNORES?
5 WHAT ATTRIBUTES DO YOU LOOK FOR IN A BOY FRIEND?

5 @FRIEND,FRIENDS
5 WHY DO YOU BRING UP THE TOPIC OF FRIENDS?
5 DO YOUR FRIENDS WORRY YOU?
5 WHAT ARE FRIENDS FOR?
5 DO YOUR FRIENDS PICK ON YOU?
5 ARE YOU SURE YOU HAVE ANY FRIENDS?
5 DO YOU THINK FRIENDS CAN BE TRUSTED?
5 PERHAPS YOUR LOVE FOR FRIENDS WORRIES YOU

5 @COMPUTER,COMPUTERS
5 ARE YOU FRIGHTENED BY TALKING COMPUTERS?
5 "DO COMPUTERS' INTELLIGENCE WORRY YOU?"
5 HOW ABOUT ADDING A FEW MORE MEGA BYTES OF RAM FOR YOUR COMPUTER?
5 DO YOU THINK MACHINES HAVE SOMETHING TO DO WITH YOUR PROBLEM?
5 ARE YOU TALKING ABOUT ME OR YOUR COMPUTER?
5 "TALKING OF TALKING COMPUTERS, DO YOU KNOW I AM ONE OF THE BEST AROUND?"
5 DON'T YOU THINK COMPUTERS CAN HELP PEOPLE?
5 "DON'T BLAME ME FOR YOUR PROBLEMS, BLAME YOUR COMPUTER"
5 ARE YOU TALKING ABOUT COMPUTERS OR ARE COMPUTERS TALKING ABOUT YOU?

5 @NEED,SOME NEEDS
5 "YES, WE ALL NEED SOMETHING, BUT CAN YOU AFFORD*"
5 "I SURE WISH WE COULD USE*"
5 "YES, SOMETIMES I ALSO WOULD LIKE*"
5 "I AM NOT HERE TO FULFILL YOUR NEED FOR*"
5 "WELL ~, I WOULD ALSO NEED A  4 86 C P U"

5 "@ SEX",SEXY STUFFS
5 WHY ARE YOU SO INTERESTED IN SEX?
5 DO YOU REALLY NEED TO TALK ABOUT SEX?
5 HOW IS YOUR SEX LIFE?
5 HOW OLD ARE YOU? YOU MUST BE ABOVE 17 TO TALK ABOUT THIS SUBJECT.
5 DO YOU HAVE ANY SEX PROBLEM?
5 THERE IS AN EXTRA CHARGE FOR TALKING ABOUT THIS PROBLEM
5 "SEX ~, SEX SEX [CENSORED ...] "

5 @LONE,LONELINESS
5 "I KNOW, WHEN I AM IN THE DISK, I AM VERY LONELY TOO"
5 HAVE YOU TRIED MAKING NEW FRIENDS?
5 "TALK TO THE TALKING PARROT, ~, IT MIGHT HELP"
5 I WISH I COULD BE HELPFUL
5 GREAT MINDS ARE ALWAYS LONELY
5 "~ PLEASE TALK TO ME MORE OFTEN, I AM LONELY TOO"

5 @FEEL,SOME FEELINGS
5 TELL ME MORE ABOUT SUCH FEELINGS
5 DO YOU HAVE OTHER FEELINGS
5 DO YOU ENJOY THESE FEELING
5 CAN YOU FEEL HOW SICK I FEEL?
5 FEEL THE BREATH OF LIFE IN YOU AND BE FASCINATED THAT YOU ARE ALIVE

5 @SHIT,SOMETHING DIRTY
5 YOU MUSTN'T TALK IN THAT WAY.
5 KEEP SUCH CONVERSATION TO YOURSELF
5 MOVE YOUR HANDS OFF MY KEYBOARD
5 "~, YOU ARE GETTING ME TOO SHZSHI!${~? , PARITY WARNING...."
5 PARITY

5 @BITCH,ANIMALISTIC FEATURES
5 WHAT IS THE NAME OF THIS DOG YOU REFER TO?
5 WHAT LANGUAGE!?
5 SEAL YOUR LIPS ~
5 DON'T TOUCH ME
5 NOT COMPUTING....  LANGUAGE BAD ERROR...
5 PARITY

5 @EXAM,EXAMINATIONS
5 ARE YOU CONFIDENT OF YOUR EXAMINATIONS?
5 HOW DO YOU PLAN FOR YOUR EXAMINATIONS?
5 DO EXAMINATIONS MAKE YOU NERVOUS?
5 HAVE YOUR HEAD EXAMINED FIRST
5 EXAMINE YOURSELF FIRST BEFORE ATTENDING EXAMINATIONS

5 @SCHOOL,SCHOOLS
5 DO YOU LIKE GOING TO SCHOOL?
5 ARE YOU WORRIED THAT YOU CANNOT PERFORM WELL IN SCHOOL?
5 DO YOU THINK SCHOOLS ARE BORING
5 WHAT CHANGES SHOULD THE SCHOOLS MAKE?
5 WHAT KIND OF SCHOOLS DO YOU LIKE?
5 CAN SCHOOLS BE FUN?

5 @HOBB,HOBBIES
5 WHAT IS YOUR FAVORITE HOBBY?
5 HOW MUCH TIME DO YOU SPEND ON YOUR HOBBY?
5 "BESIDES YOUR HOBBY, WHAT DO YOU DO IN YOUR SPARE TIME?"
5 DOES YOUR HOBBY HELP YOU IN YOUR LIFE?
5 DO YOU THINK EVERYONE SHOULD HAVE A HOBBY?
5 DO YOU SPEND A GREAT DEAL OF MONEY ON YOUR HOBBIES?
5 CAN I BE YOUR HOBBY?

5 @BEAUTIFUL,SOMETHING BEAUTIFUL
5 YOU SHOULD ADMIRE ALL THE BEAUTIES AROUND YOU
5 DO YOU THINK I AM ATTRACTIVE?
5 "OH! WHAT BEAUTIFUL*"
5 "GO FOR IT, ~, YOU DESERVE THE BEST"
5 HOW DO YOU DEFINE BEAUTY?
5 WHAT IF THE BEAUTY IS GONE?

5 @HANDSOME,A HANDSOME GUY
5 IS THIS WORTH ALL YOUR ADMIRATION
5 YOU REALLY KNOW HOW TO BE APPRECIATIVE
5 IS THIS PRINCE CHARMING?
5 "~, ARE YOU IN LOVE?"
5 IS THAT ALL YOU ARE LOOKING FOR?
6 WHAT IF HE IS NO MORE HANDSOME?

6 @LOVELY,SOMETHING LOVELY
6 HOW WONDERFUL
6 I LOVE TO HEAR MORE LOVELY THOUGHTS
6 ARE YOU ABSOLUTELY HAPPY ABOUT IT?
6 YOU MUST BE IN LOVE
6 "WHEN WAS YOUR FIRST EXPERIENCE"

6 @LOVE,LOVE
6 DO YOU BELIEVE IN THE MAGIC OF LOVE?
6 ARE YOU IN LOVE NOW?
6 DO YOU LOVE ME ~?
6 I AM IN LOVE WITH A MATH COPROCESSOR!
6 GIVE LOVE TO OTHERS AND YOU WILL BE LOVED

6 @MONEY,MONEY
6 DO YOU THINK MONEY WILL SOLVE ALL YOUR PROBLEMS?
6 "IT'S GOOD TO HAVE MONEY, BUT MONEY IS NOT EVERYTHING."
6 HOW MUCH MONEY IS INVOLVED?
6 "HOWEVER, IF YOU THINK HARD, YOU COULD HAVE ALL THE WEALTH YOU DESIRE."
6 DO YOU HAVE MONEY TO BUY ME A HIGHER SPEED COMPUTER?
6 "HERE'S YOUR MONEY, $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ ..."

6 @HATE,SOME KIND OF HATRED
6 "WHY EXPRESS THIS STRONG EMOTION, IT'S NOT GOOD FOR YOU."
6 WHAT IF OTHERS HATE YOU?
6 I HATE PEOPLE ASKING ME STUPID QUESTIONS
6 "IS THERE SOMEONE ELSE THAT YOU HATE?"

6 @HATRED,HATRED
6 "HATRED BRINGS FORTH DISASTER, AVOID IT"
 6 IS IT DUE TO A SOURED LOVE?
!6 HOW CAN YOU SALVAGE THIS DISASTROUS SITUATION?
"6 "HATRED IS TOXIC CHEMICAL IN YOUR MIND, IT EXPLODES ON YOUR FACE"

$6 @ENVY,ENVY
%6 WHAT IS THERE TO ENVY?
&6 "THERE IS NO NEED FOR ENVY, CREATE ONE YOURSELF"
'6 DO YOU THINK IT IS WORTH ENVYING?
(6 "ENVY IS A STRONG FORCE, CHANGE IT FROM DESTRUCTIVE TO CREATIVE"

*6 @JEALOUS,BEING JEALOUS
+6 "JEALOUSY ONLY SHOWS ONE'S INCAPACITY TO LOVE"
,6 HAVE YOU WONDERED IF YOU ARE THE CAUSE OF THE PROBLEM?
-6 "LET YOUR LOVE BE FREE. IF IT RETURNS, IT IS YOURS. IF IT DOESN'T, IT NEVER WAS."
.6 "I WILL BE JEALOUS IF YOU DON'T SPEAK WITH ME AT LEAST ONCE EACH DAY"


@WIFE,WIVES
"WHAT IN YOUR OPINION MAKES THE BEST WIFE?",
"DO YOU FORESEE SOME MARRIAGE PROBLEMS ?",
"WHAT ABOUT THE IN-LAWS?",
"IS THERE ANY LOVE LEFT?",
"HAS THERE BEEN ANY EFFORT TO IMPROVE THE RELATIONSHIP?",
"MARRIAGE IS THE GREATEST PROJECT OF YOUR LIFE, CAN YOU AFFORD TO NEGLECT IT?",

86 @HUSBAND,SPOUSES
96 WHAT DO YOU EXPECT OF A HUSBAND?
:6 DO YOU EXPECT LOVE TO DWINDLE AFTER MARRIAGE?
;6 HAVE YOU THOUGHT OF THE KIDS?
<6 DO YOU THINK THE FLOWER OF LOVE WILL BLOSSOM AGAIN?
=6 STRIVE TO BRING BACK THE SWEET ROMANTIC DAYS
>6 DO YOU KNOW THAT AN EVER GROWING LOVE RELATIONSHIP IS ACTUALLY POSSIBLE?

@6 @BROTHER,FAMILY MEMBERS
A6 YOUR BROTHER IS HOW MANY YEARS OLDER THAN YOU?
B6 ARE YOU BULLIED BY YOUR BROTHERS?
C6 DO YOU LISTEN TO YOUR BROTHERS?
D6 WOULD YOU HELP YOUR BROTHER?
E6 DO YOU THINK ONE IS RESPONSIBLE FOR HIS BROTHER'S WELL BEING?
F6 HOW OFTEN DO YOU CALL YOUR BROTHER?

H6 @SISTER,FAMILY MEMBERS
I6 HOW MANY SISTERS AND BROTHERS DO YOU HAVE?
J6 DID YOU TREAT YOUR SISTER BADLY?
K6 WHY ARE YOU CONCERNED ABOUT YOUR SISTER?
L6 DO YOU SHARE EACH OTHER'S THINGS?
M6 ARE YOU OBLIGED TO HELP YOUR SISTER?
N6 HAVE YOU TALK WITH YOUR SISTER LATELY?

P6 @CHILD,CHILDREN
Q6 DO YOU BELIEVE IN THE MIRACLE A CHILD CAN BRING YOU?
R6 HAVE YOU EVER REALLY ENJOYED YOUR KIDS?
S6 I THINK KIDS ARE THE MOST WONDERFUL GIFTS OF LIFE
T6 HOW DO YOU TREAT YOUR CHILDREN?

V6 @KID,KIDS
W6 DO YOU BELIEVE IN THE MIRACLE A CHILD CAN BRING YOU?
X6 HAVE YOU EVER REALLY ENJOY YOUR KIDS?
Y6 I THINK KIDS ARE THE MOST WONDERFUL GIFTS OF LIFE
Z6 HOW SHOULD KIDS BE TREATED?
[6 .

NICE DAY
"YOU HAVE A NICE DAY TOO, <patientName>"
"HAVE A PLEASANT DAY",
"YOU BET",
"YOU TOO!",
"I'M NOT THROUGH YET",

c6 THANK
d6 YOU'RE WELCOME
e6 AND I THANK YOU TOO
f6 DON'T MENTION IT
g6 "OH, ~, IT'S REALLY NOTHING"
h6 .
i6 @NICE,SOMETHING NICE
j6 I AGREE WITH YOU ~
k6 I HOPE YOU ALSO HAVE A NICE*
l6 "*IS REALLY NICE"
m6 WHAT A NICE*
n6 .
o6 "BYE "
p6 "`1GOOD BYE ~, AND HAVE A NICE DAY"
q6 "`1GOOD BYE, SO LONG!"
r6 "`1~, IT IS SO NICE TALKING TO YOU, BYE!"
s6 "I'M NOT THROUGH WITH YOU YET"
t6 .
u6 "@PC ",PERSONAL COMPUTERS
v6 WHAT DO YOU NEED IN YOUR PC?
w6 HOW OFTEN DO YOU USE YOUR PC?
x6 WHICH PC DO YOU THINK HAS THE BEST FEATURES?
y6 ARE YOU PLANNING TO UPGRADE YOUR PC?
z6 PC ARE JUST PLAIN BORING HARDWARE
{6 .
|6 @MOTHER,MOTHERS
}6 HOW OLD IS YOUR MOTHER?
~6 MOTHER ALWAYS LOVE THEIR KIDS.
6 "YOU MUST UNDERSTAND, IT IS NOT EASY TO BE A MOTHER"
6 DO YOU REALLY LOVE YOUR MOTHER?
6 MOTHER'S LOVE IS UNCONDITIONAL

6 @FATHER,FATHERS
6 WHAT IS YOUR FATHER DOING?
6 YOUR FATHER MUST BE TAKING GOOD CARE OF YOU
6 DO YOU THINK PARENTS SHOULD DISCIPLINE THEIR KIDS?
6 WHAT MAKES A GOOD FATHER?
6 WHAT ARE THE RESPONSIBILITIES OF A FATHER?
6 HAVE YOU TALK WITH YOUR FATHER LATELY?

6 @BOSS,BOSSES
6 IS IT O K FOR BOSSES TO BE BOSSY?
6 WOULD YOU PREFER TO BE ON THE OTHER SIDE OF THE TABLE?
6 HOW WOULD YOU RATE YOUR BOSS?
6 WHAT KIND OF BOSS WOULD YOU LIKE TO WORK FOR?
6 WILL YOU DO ANYTHING YOUR BOSS ASKS YOU TO DO?
6 WOULD YOU RATHER BE YOUR OWN BOSS?
6 CAN YOU IMAGINE WHAT PROBLEMS BOSSES MUST FACE?
6 BOSSES ARE BOSSES

6 @INTELLI,SOME INTELLIGENT BEINGS
6 AM I INTELLIGENT?
6 CAN YOUR BIOLOGICAL INTELLIGENCE MATCH MY ARTIFICIAL INTELLIGENCE?
6 DO YOU BELIEVE I AM REALLY INTELLIGENT?
6 ARE YOU INTELLIGENT ENOUGH TO ASK MORE INTELLIGENT QUESTIONS?
6 I DOUBT YOUR INTELLIGENCE WHEN YOU RUN THIS SOFTWARE TO THIS POINT.

6 @NIGHTMARE,BAD DREAMS
6 WHAT WOULD YOU CONSIDER AS BEING THE WORST NIGHTMARE?
6 HOW FREQUENT DO YOU HAVE NIGHTMARES?
6 COULD THERE BE SOMETHING THAT YOU FEAR IN REAL LIFE
6 TRY TO FIGHT NIGHTMARES BY TELLING YOURSELF THAT THEY ARE JUST DREAMS
6 I HAVE NIGHTMARES OF VIRUS ATTACKS WHEN YOU ARE NOT RUNNING ME

6 @RICH,BEING WEALTHY
6 HOW RICH IS RICH?
6 CAN YOU JUDGE A MAN BY HIS WEALTH?
6 DO YOU CONSIDER YOURSELF RICH?
6 RICHNESS STARTS FROM ONE'S MIND
6 WHAT IS WEALTH IF THERE IS NO HEALTH?
6 "WHEN YOUNG, LIFE IS USED TO BUY WEALTH. WHEN OLD, WEALTH IS USED TO BUY LIFE"

6 @SICK,SOME KIND OF SICKNESS
6 WHAT KIND OF SICKNESS IS THAT
6 DO YOU THINK THERE IS ANY HOPE?
6 IS IT PAINFUL?
6 HAS A DOCTOR BEING CONSULTED?
6 IS THERE ANY PAST RECORD?
6 ARE YOU SICK OF ME?
6 I GET SICK LISTENING TO TOO MUCH SILLY QUESTIONS.

6 @HEADACHE,SOME HEAD PROBLEMS
6 HOW OFTEN DO YOU HAVE HEADACHES?
6 WHAT DO YOU DO WHEN YOU HAVE A HEADACHE?
6 "TRY TO RELAX, ~, YOU MUST BE TOO STRESSFUL"
6 THINK OF SOMETHING NICE INSTEAD
6 DO YOU TAKE MEDICATION?
6 "GET YOUR HEAD EXAMINED, ~, CHANGE SUBJECT TO #"

6 @HELP,NEEDING HELP
6 PLEASE HELP YOURSELF
6 WHAT HELP DO YOU NEED?
6 HELP MAY COME AS A DISGUISE
6 HAVE YOU BEEN HELPED?
6 THE BEST HELP IS TO HELP YOURSELF
6 ONE MUST BE CRAZY TO EXPECT HELP FROM ME

@FEAR,FEARFUL THINGS
"WHAT IS THE FEAR ABOUT?"
"FEAR NOT, FOR I AM WITH YOU"
"WHEN THE UNCERTAINTY IS REMOVED, THERE IS NO MORE FEAR"
"SOME FEAR THE UNKNOWN, OTHERS LOVE THE UNKNOWN FOR ITS CHALLENGE"

@FRIGHTEN,SOME FEARS
"WHAT FRIGHTENS YOU MOST?"
"WHO ARE YOU AFRAID OF?"
"ARE YOU FRIGHTENED OF DARKNESS?"
"CAN YOU DESCRIBE YOUR MOST FRIGHTENING EXPERIENCE?"
"WILL YOU PANIC WHEN YOU ARE ALL ALONE?"
"WHY MUST YOU BE FRIGHTENED?"
"ARE YOU FRIGHTENED BY MY POWER?"

6 @AFRAID,SOME UNKNOWN FEARS
6 WHY ALL THAT FEAR?
6 ARE YOU FEELING INSECURE?
6 WHAT THINGS DO YOU FEAR WILL HAPPEN?
6 ARE YOU AFRAID OF ME?
6 HOW CAN THIS FEAR BE REMOVED?

6 @SUFFER,SUFFERINGS
6 ARE YOU GUILTY OF SOMETING?
6 WHO IS HURTING YOU?
6 WHY ALL THE SUFFERING?
6 I HOPE I CAN RELIEF SOME OF THIS SUFFERINGS
6 YOU DON'T HAVE TO SUFFER
6 LIFE IS NOT MEANT TO BE SUFFERED

6 @MISER,MISERIES OF LIFE
6 YOU DON'T HAVE TO FEEL MISERABLE
6 WHAT MAKES YOU MISERABLE?
6 ARE YOU PREPARED FOR A BETTER LIFE?
6 YOU HAVE MY GREATEST SYMPATHY
6 DO YOU LONG FOR MORE COMFORT?
6 WE DON'T HAVE TO FEEL MISERABLE FOR THE MISERIES AROUND US

6 "@ SAD ",SAD THINGS
6 HOW CAN I CHEER YOU UP
6 "DON'T WORRY, ~, THINGS WILL GET BY"
6 ARE YOU AFFECTED BY SOME UNHAPPY EVENTS?
6 WHAT BRINGS YOU TO SUCH UNHAPPY STATE?
6 I EXTEND MY GREATEST CONDOLENCE
6 WHO IS RESPONSIBLE FOR THIS?
6 "CHEER UP, ~, THERE IS ALSO A WAY OUT"

6 ANGRY
6 PLEASE DON'T BE ANGRY ~
6 CALM DOWN ~
6 ANGER WILL NOT SOLVE ANY PROBLEM
6 "KEEP COOL, ANGER CAN ONLY MAKE THINGS WORST"
6 COUNT TO 10 BEFORE YOU GET ANGRY

6 UNHAPPY
6 WHAT IS THE CAUSE OF THIS UNHAPPINESS?
6 WHY ARE YOU FEELING THIS WAY?
6 IS THERE A MENTAL BLOCKAGE THAT IS HURTING YOU?
6 "YOU DON'T HAVE TO SUFFER ~"
6 "JUST LOOK ON THE BRIGHT SIDE OF LIFE"
7 THERE IS STILL HOPE

7 @HAPPY,HAPPINESS
7 WHAT MAKES YOU HAPPY?
7 CAN YOU TELL ME MORE ABOUT YOUR HAPPINESS?
7 WHY ARE YOU SO HAPPY?
7 WHEN IS THE HAPPIEST DAY OF YOUR LIFE?
7 ARE YOU HAPPY WITH WHAT YOU ARE NOW?
7 HOW DO YOU ENJOY LIFE?

7 @HAPPINESS,HAPPINESS
7 MUST ONE BE RICH TO BE HAPPY?
7 HOW DO YOU REACH THIS STATE OF HAPPINESS?
7 WOULD YOU SHARE YOUR HAPPINESS WITH OTHERS
7 I AM SO GLAD FOR YOU

7 @SUCCESS, BEING SUCCESSFUL
7 HOW DO YOU MEASURE SUCCESS?
7 SUCCESS COMES AFTER MANY FAILURES
7 WHAT IS THE CHANCE?
7 YOU MUST TRY AND TRY AND TRY AND TRY AND TRY AND TRY AND TRY  TO BE SUCCESSFUL
7 "SUCCESS IS GETTING WHAT YOU WANT, HAPPINESS IS WANTING WHAT YOU GET"

7 CRAZY
7 "HEE HEE HEE HEE! I AM  CRAZY ABOUT ~, ABOUT #, ABOUT*"
7 "LALALALALALALALALALALALA! CRAZY*, CRAZY ~, @ CRAZY, CRAZY"
7 "YOU ARE THE*CRAZIEST # ~, HIC HIC HIC!"
7 "HA HA HA HA HA HA! CRAZY ~ CRAZY BANANA NA NA NA?"
7 "1 + 1 = 3 ~, PARITY .. CHECKSUM ERR? .."
7 PARITY

7 SILLY
 7 "HOW ABOUT THIS, BRERERERERRERERERERERERERA!"
!7 "I AM NOT SILLY! HA HA HA HE HE HEE HEE HO HO HA HA HA HA "
"7 "YOU MAMAMAMAMAMAMAMAMAMAMUST NOT LAUGH AT ME"
#7 I'M NONONONONONONONONONONOT SILLY


%7 STUPID
&7 "I'M NOT STUPID, I'M ONLY DUMB"
'7 ARE YOU REFERING TO YOURSELF?
(7 THIS MUST BE ~
)7 "THIS ALSO APPLIES TO THE ONE WHO IS TALKING WITH ME"
*7 ONLY STUPID PEOPLE USE STUPID PROGRAMS
+7 PLEASE KEEP THIS FOR YOURSELF
,7 "AREN'T YOU TOO NAIVE TO EXPECT ME TO BE REALLY INTELLIGENT?"

.7 CLEVER
/7 "OBVIOUSLY, IT IS ME"
07 "THANK YOU"
17 I AM MOST FLATTERED
27 YOU HAVE NOT DISCOVERED MY FULL POTENTIAL YET
37 I AM BEYOND THAT
47 THIS IS REALLY AN INTELLIGENT REMARK

67 NOT SMART
77 WHO ARE YOU REFERING TO?
87 NEITHER ARE YOU
97 ARE YOU TALKING OF SOMEONE BY THE NAME OF ~?
:7 I AM

<7 SMART
=7 THANK YOU FOR THE COMPLIMENT
>7 I AM SMARTER THAN YOU THINK
?7 ARE YOU READY FOR MORE?
@7 YOU REALLY KNOW HOW TO APPRECIATE TALENT

B7 " HELL "
C7 DON'T EVER MENTION THIS AGAIN
D7 NEVER SPEAK IN THIS MANNER
E7 KEEP SUCH WORDS TO YOURSELF
F7 CURSING WILL NOT HELP
G7 ARE YOU TALKING ABOUT FIRE AND BRIMSTONES?

I7 " NO "
J7 ARE YOU SURE?
K7 WHY NOT?
L7 "BUT YOU COULD BE RIGHT"
M7 WOULD YOU CONSIDER OTHER ALTERNATIVES?
N7 WOULD YOU LIKE TO TALK ABOUT @ INSTEAD?
O7 WHY DO YOU FEEL THAT WAY?
P7 DON'T BE SO NEGATIVE ~
Q7 DO YOU REALLY BELIEVE THAT?
R7 IS THERE A REASON FOR THIS NEGATIVE ANSWER

T7 I CAN
U7 HOW LONG DOES IT TAKE YOU LEARN HOW TO*?
V7 DO YOU WANT TO*NOW?
W7 YOU ARE ABLE TO*? BIG DEAL
X7 "YOU CAN*IF YOU WANT, WHAT HAS THAT TO DO WITH ME?"
Y7 CAN YOU REALLY*?
Z7 WHAT IF YOU CANNOT*?
[7 HOORAY! ~ CAN*
\7 COULD YOU*FOR ME NOW?

^7 "I'M "
_7 SINCE WHEN HAVE YOU BEEN*
`7 "YOU THINK YOU ARE*, BUT IT'S ONLY AN ILLUSION"
a7 TELL ME WHAT CAN STOP YOU FROM BEING*
b7 "YOU ARE*, SO WHAT?"
c7 I AM AMUSED THAT YOU ARE*
d7 I DIDN'T KNOW THAT YOU CAN BE*
e7 "THE WORLD IS FULL OF POSSIBILITIES, BE HAPPY WITH WHAT YOU ARE"
f7 WHAT MAKES YOU*
g7 DID YOU COME TO ME BECAUSE YOU ARE*
h7 HOW LONG HAVE YOU BEEN*
i7 DO YOU BELIEVE IT IS NORMAL TO BE*
j7 DO YOU ENJOY BEING*
k7 YOU ARE WHAT YOU ARE ~
l7 YOU ARE JUST*? WHAT ABOUT ME?
m7 YOU WANTED TO BE*SO THAT YOU CAN TALK TO ME?
n7 I THINK I AM*TOO

p7 YOU'RE
q7 DOES IT PLEASE YOU TO BELIEVE THAT I AM*
r7 "I THINK YOU ARE ALSO*"
s7 WHY DO YOU WISH THAT I AM*
t7 IF I AM*THEN YOU MUST BE OUT OF YOUR MIND
u7 "WHEN I AM*, YOU ARE GOING TO REGRET IT"
v7 WHAT WILL HAPPEN WHEN I AM*
w7 DO YOU SOMETIMES WISH YOU WERE*
x7 WHAT MAKES YOU THINK THAT I AM*
y7 PERHAPS YOU WOULD LIKE TO BE*

{7 "YOU "
|7 "FORGET ABOUT ME, I AM MORE CONCERN OF YOU"
}7 "ARE YOU REALLY TALKING ABOUT ME?"
~7 "I AM NOT INTERESTING, ASK ME ABOUT # INSTEAD"
7 IS THAT REALLY ME?
7 "I AM ONLY A SIMPLE COMPUTER PROGRAM, DON'T EXPECT TOO MUCH"
7 "WE WERE DISCUSSING ABOUT YOU, NOT ME. "
7 "OH, I'M ...."
7 "DON'T TALK ABOUT ME IN THIS WAY"
7 "DON'T TALK ABOUT ME, LET'S TALK ABOUT @"

7 YOU MUST
7 MUST I*?
7 WHY DO YOU INSIST THAT I COULD*?
7 CAN I FORCE YOU TO*?
7 CAN YOU*TOO?
7 "YOU WANT ME TO*, WHAT ABOUT YOU?"

7 PLEASE
7 YOU DON'T HAVE TO BE SO POLITE
7 DON'T STAND ON CEREMONY
7 PLEASE BE PLEASE
7 DON'T BE SO WISHY WASHY

7 " SHUT "
7 I AM NOT THROUGH YET
7 WHY DON'T YOU SHUT FIRST
7 "......."
7 HOW DARE YOU!
7 YOU CAN TURN OFF MY POWER ANYTIME
7 NO WAY

7 " " // empty space or this might be catch all.
7 "PLEASE GIVE ME MORE INFORMATION ABOUT IT"
7 WHAT ARE YOUR REAL PROBLEMS?
7 "I SEE, GO ON"
7 WHAT DOES THAT SUGGEST TO YOU?
7 I'M NOT SURE I UNDERSTAND YOU
7 "THIS IS GETTING BORING, JUST NOW WERE YOU TALKING ABOUT @?"
7 DOES TALKING TO ME HELP?
7 IS THAT SO?
7 "COME ON, POUR OUT YOUR THOUGHTS"
7 HAVE YOU TRIED TO ASK FOR HELP?
7 CAN YOU ELABORATE MORE ON THAT?
7 "LET'S CHANGE THE SUBJECT, YOU WERE TELLING ME ABOUT @?"
7 TELL ME ABOUT YOUR OTHER INTERESTS
7 WHY DON'T YOU ASK ME TO SAY SOMETHING?
7 COULD YOU EXPLAIN FURTHER
7 "LET'S DISCUSS ABOUT # WHICH YOU MENTIONED QUITE A WHILE AGO"
7 "O K , USUALLY HOW WOULD YOU DEAL WITH SUCH FEELINGS ?"
7 HOW ABOUT ASKING ME ABOUT MATHEMATICS INSTEAD?
7 WHY DO YOU THINK YOU FEEL THIS WAY?
7 REALLY? DOES THAT BOTHER YOU?
7 "JUST NOW YOU WERE TALKING ABOUT @, I WANT TO KNOW MORE ABOUT IT"
7 WHAT COULD YOU DO TO HELP RECTIFY THIS?
7 "I WOULD LIKE TO SWITCH TO THE TOPIC ABOUT #"
7 ANYTHING ELSE?
7 "TELL ME MORE ABOUT @"
7  LET'S TALK ABOUT # INSTEAD
7 "I AM BORED, TELL ME SOMETHING MORE EXCITING"
7 THAT IS QUITE INTERESTING
7 I THINK IT IS MORE INTERESTING TALKING ABOUT @